# HL7 Segment and Field Definitions
# Based on parsehog's HL7Definitions

HL7_SEGMENTS = {
    'ABS': 'Abstract',
    'ACC': 'Accident',
    'ADD': 'Addendum',
    'ADJ': 'Adjustment',
    'AFF': 'Professional Affiliation',
    'AIG': 'Appointment Information - General Resource',
    'AIL': 'Appointment Information - Location Resource',
    'AIP': 'Appointment Information - Personnel Resource',
    'AIS': 'Appointment Information - Service Resource',
    'AL1': 'Patient Allergy Information',
    'APR': 'Appointment Preferences',
    'ARQ': 'Appointment Request',
    'ARV': 'Access Restriction',
    'AUT': 'Authorization Information',
    'BHS': 'Batch Header',
    'BLC': 'Blood Code',
    'BLG': 'Billing',
    'BPO': 'Blood Product Order',
    'BPX': 'Blood Product Dispense Status',
    'BTX': 'Blood Product Transfusion/Disposition',
    'BUI': 'Blood Unit Information',
    'CDM': 'Charge Description Master',
    'CDO': 'Clinical Study with Phases and Schedules',
    'CER': 'Certificate Detail',
    'CM0': 'Clinical Study Master',
    'CM1': 'Clinical Study Phase Master',
    'CM2': 'Clinical Study Schedule Master',
    'CNS': 'Clear Notification',
    'CON': 'Consent Segment',
    'CSP': 'Clinical Study Phase',
    'CSR': 'Clinical Study Registration',
    'CSS': 'Clinical Study Data Schedule Segment',
    'CTD': 'Contact Data',
    'CTI': 'Clinical Trial Identification',
    'DB1': 'Disability',
    'DG1': 'Diagnosis',
    'DMI': 'DRG Master File Information',
    'DON': 'Donation Segment',
    'DRG': 'Diagnosis Related Group',
    'DSC': 'Continuation Pointer',
    'DSP': 'Display Data',
    'ECD': 'Equipment Command',
    'ECR': 'Equipment Command Response',
    'EDU': 'Educational Detail',
    'EQP': 'Equipment/log Service',
    'EQU': 'Equipment Detail',
    'ERR': 'Error',
    'EVN': 'Event Type',
    'FAC': 'Facility',
    'FHS': 'File Header',
    'FT1': 'Financial Transaction',
    'FTS': 'File Trailer',
    'GOL': 'Goal Detail',
    'GP1': 'Grouping/Reimbursement - Visit',
    'GP2': 'Grouping/Reimbursement - Procedure Line Item',
    'GT1': 'Guarantor',
    'IAM': 'Patient Adverse Reaction Information',
    'IAR': 'Allergy Reaction',
    'IIM': 'Inventory Item Master',
    'ILT': 'Material Lot',
    'IN1': 'Insurance',
    'IN2': 'Insurance Additional Information',
    'IN3': 'Insurance Additional Information, Certification',
    'INV': 'Inventory Detail',
    'IPC': 'Imaging Procedure Control Segment',
    'IPR': 'Invoice Processing Results',
    'ISD': 'Interaction Status Detail',
    'ITM': 'Material Item',
    'IVC': 'Invoice Segment',
    'IVT': 'Material Location',
    'LAN': 'Language Detail',
    'LCC': 'Location Charge Code',
    'LCH': 'Location Characteristic',
    'LDP': 'Location Department',
    'LOC': 'Location Identification',
    'LRL': 'Location Relationship',
    'MFA': 'Master File Acknowledgment',
    'MFE': 'Master File Entry',
    'MFI': 'Master File Identification',
    'MRG': 'Merge Patient Information',
    'MSA': 'Message Acknowledgment',
    'MSH': 'Message Header',
    'NCK': 'System Clock',
    'NDS': 'Notification Detail',
    'NK1': 'Next of Kin / Associated Parties',
    'NPU': 'Bed Status Update',
    'NSC': 'Application Status Change',
    'NST': 'Application Control Level Statistics',
    'NTE': 'Notes and Comments',
    'OBR': 'Observation Request',
    'OBX': 'Observation/Result',
    'ODS': 'Dietary Orders, Supplements, and Preferences',
    'ODT': 'Diet Tray Instructions',
    'OM1': 'General Segment',
    'OM2': 'Numeric Observation',
    'OM3': 'Categorical Service/Test/Observation',
    'OM4': 'Observations that Require Specimens',
    'OM5': 'Observation Batteries (Sets)',
    'OM6': 'Observations that are Calculated from Other Observations',
    'OM7': 'Additional Basic Attributes',
    'ORC': 'Common Order',
    'ORG': 'Practitioner Organization Unit',
    'OVR': 'Override Segment',
    'PAC': 'Shipment Packaging',
    'PCE': 'Patient Charge Cost Center Exceptions',
    'PCR': 'Possible Causal Relationship',
    'PD1': 'Patient Additional Demographic',
    'PDA': 'Patient Death and Autopsy',
    'PDC': 'Product Detail Country',
    'PEO': 'Product Experience Observation',
    'PES': 'Product Experience Sender',
    'PID': 'Patient Identification',
    'PKG': 'Item Packaging',
    'PMT': 'Payment Information',
    'PR1': 'Procedures',
    'PRA': 'Practitioner Detail',
    'PRB': 'Problem Details',
    'PRC': 'Pricing',
    'PRD': 'Provider Data',
    'PRT': 'Participation Information',
    'PSG': 'Product/Service Group',
    'PSH': 'Product Summary Header',
    'PSL': 'Product/Service Line Item',
    'PSS': 'Product/Service Section',
    'PTH': 'Pathway',
    'PV1': 'Patient Visit',
    'PV2': 'Patient Visit - Additional Information',
    'PYE': 'Payee Information',
    'QAK': 'Query Acknowledgment',
    'QID': 'Query Identification',
    'QPD': 'Query Parameter Definition',
    'QRD': 'Original-Style Query Definition',
    'QRF': 'Original style query filter',
    'QRI': 'Query Response Instance',
    'RCP': 'Response Control Parameter',
    'RDF': 'Table Row Definition',
    'RDT': 'Table Row Data',
    'REL': 'Clinical Relationship Segment',
    'RF1': 'Referral Information',
    'RFI': 'Request for Information',
    'RGS': 'Resource Group',
    'RMI': 'Risk Management Incident',
    'ROL': 'Role',
    'RQ1': 'Requisition Detail-1',
    'RQD': 'Requisition Detail',
    'RXA': 'Pharmacy/Treatment Administration',
    'RXC': 'Pharmacy/Treatment Component Order',
    'RXD': 'Pharmacy/Treatment Dispense',
    'RXE': 'Pharmacy/Treatment Encoded Order',
    'RXG': 'Pharmacy/Treatment Give',
    'RXO': 'Pharmacy/Treatment Order',
    'RXR': 'Pharmacy/Treatment Route',
    'RXV': 'Pharmacy/Treatment Infusion',
    'SAC': 'Specimen Container detail',
    'SCH': 'Scheduling Activity Information',
    'SCP': 'Sterilizer Configuration',
    'SDD': 'Sterilization Device Data',
    'SFT': 'Software Segment',
    'SHP': 'Shipment',
    'SID': 'Substance Identifier',
    'SLT': 'Sterilization Lot',
    'SPM': 'Specimen',
    'SPS': 'Specimen Source',
    'STF': 'Staff Identification',
    'STZ': 'Sterilization Parameter',
    'TCC': 'Test Code Configuration',
    'TCD': 'Test Code Detail',
    'TQ1': 'Timing/Quantity',
    'TQ2': 'Timing/Quantity Relationship',
    'TXA': 'Transcription Document Header',
    'UB1': 'UB82 Billing',
    'UB2': 'UB92 Uniform Billing',
    'URD': 'Results/Update Definition',
    'URS': 'Results/Update Selection Criteria',
    'VAR': 'Variance',
    'VND': 'Purchasing Vendor',
    'ZXX': 'User-defined Segment'
}

# Field definitions for each segment
HL7_FIELDS = {
    'MSH': {
        '1': 'Field Separator (always |)',
        '2': 'Encoding Characters',
        '3': 'Sending Application',
        '4': 'Sending Facility',
        '5': 'Receiving Application',
        '6': 'Receiving Facility',
        '7': 'Date/Time of Message',
        '8': 'Security',
        '9': 'Message Type',
        '10': 'Message Control ID',
        '11': 'Processing ID',
        '12': 'Version ID',
        '13': 'Sequence Number',
        '14': 'Continuation Pointer',
        '15': 'Accept Acknowledgment Type',
        '16': 'Application Acknowledgment Type',
        '17': 'Country Code',
        '18': 'Character Set',
        '19': 'Principal Language Of Message',
        '20': 'Alternate Character Set Handling Scheme',
        '21': 'Message Profile Identifier',
        '22': 'Sending Responsible Organization',
        '23': 'Receiving Responsible Organization',
        '24': 'Sending Network Address',
        '25': 'Receiving Network Address'
    },
    'EVN': {
        '1': 'Event Type Code',
        '2': 'Recorded Date/Time',
        '3': 'Date/Time Planned Event',
        '4': 'Event Reason Code',
        '5': 'Operator ID',
        '6': 'Event Occurred',
        '7': 'Event Facility'
    },
    'PID': {
        '1': 'Set ID - PID',
        '2': 'Patient ID',
        '3': 'Patient Identifier List',
        '4': 'Alternate Patient ID - PID',
        '5': 'Patient Name',
        '6': "Mother's Maiden Name",
        '7': 'Date/Time of Birth',
        '8': 'Administrative Sex',
        '9': 'Patient Alias',
        '10': 'Race',
        '11': 'Patient Address',
        '12': 'County Code',
        '13': 'Phone Number - Home',
        '14': 'Phone Number - Business',
        '15': 'Primary Language',
        '16': 'Marital Status',
        '17': 'Religion',
        '18': 'Patient Account Number',
        '19': 'SSN Number - Patient',
        '20': "Driver's License Number - Patient",
        '21': "Mother's Identifier",
        '22': 'Ethnic Group',
        '23': 'Birth Place',
        '24': 'Multiple Birth Indicator',
        '25': 'Birth Order',
        '26': 'Citizenship',
        '27': 'Veterans Military Status',
        '28': 'Nationality',
        '29': 'Patient Death Date and Time',
        '30': 'Patient Death Indicator',
        '31': 'Identity Unknown Indicator',
        '32': 'Identity Reliability Code',
        '33': 'Last Update Date/Time',
        '34': 'Last Update Facility',
        '35': 'Taxonomic Classification Code',
        '36': 'Breed Code',
        '37': 'Strain',
        '38': 'Production Class Code',
        '39': 'Tribal Citizenship',
        '40': 'Patient Telecommunication Information'
    },
    'PV1': {
        '1': 'Set ID - PV1',
        '2': 'Patient Class',
        '3': 'Assigned Patient Location',
        '4': 'Admission Type',
        '5': 'Preadmit Number',
        '6': 'Prior Patient Location',
        '7': 'Attending Doctor',
        '8': 'Referring Doctor',
        '9': 'Consulting Doctor',
        '10': 'Hospital Service',
        '11': 'Temporary Location',
        '12': 'Preadmit Test Indicator',
        '13': 'Re-admission Indicator',
        '14': 'Admit Source',
        '15': 'Ambulatory Status',
        '16': 'VIP Indicator',
        '17': 'Admitting Doctor',
        '18': 'Patient Type',
        '19': 'Visit Number',
        '20': 'Financial Class',
        '21': 'Charge Price Indicator',
        '22': 'Courtesy Code',
        '23': 'Credit Rating',
        '24': 'Contract Code',
        '25': 'Contract Effective Date',
        '26': 'Contract Amount',
        '27': 'Contract Period',
        '28': 'Interest Code',
        '29': 'Transfer to Bad Debt Code',
        '30': 'Transfer to Bad Debt Date',
        '31': 'Bad Debt Agency Code',
        '32': 'Bad Debt Transfer Amount',
        '33': 'Bad Debt Recovery Amount',
        '34': 'Delete Account Indicator',
        '35': 'Delete Account Date',
        '36': 'Discharge Disposition',
        '37': 'Discharged to Location',
        '38': 'Diet Type',
        '39': 'Servicing Facility',
        '40': 'Bed Status',
        '41': 'Account Status',
        '42': 'Pending Location',
        '43': 'Prior Temporary Location',
        '44': 'Admit Date/Time',
        '45': 'Discharge Date/Time',
        '46': 'Current Patient Balance',
        '47': 'Total Charges',
        '48': 'Total Adjustments',
        '49': 'Total Payments',
        '50': 'Alternate Visit ID',
        '51': 'Visit Indicator',
        '52': 'Other Healthcare Provider',
        '53': 'Service Episode Description',
        '54': 'Service Episode Identifier'
    },
    'NK1': {
        '1': 'Set ID - NK1',
        '2': 'Name',
        '3': 'Relationship',
        '4': 'Address',
        '5': 'Phone Number',
        '6': 'Business Phone Number',
        '7': 'Contact Role',
        '8': 'Start Date',
        '9': 'End Date',
        '10': 'Next of Kin / Associated Parties Job Title',
        '11': 'Next of Kin / Associated Parties Job Code/Class',
        '12': 'Next of Kin / Associated Parties Employee Number',
        '13': 'Organization Name - NK1',
        '14': 'Marital Status',
        '15': 'Administrative Sex',
        '16': 'Date/Time of Birth',
        '17': 'Living Dependency',
        '18': 'Ambulatory Status',
        '19': 'Citizenship',
        '20': 'Primary Language',
        '21': 'Living Arrangement',
        '22': 'Publicity Code',
        '23': 'Protection Indicator',
        '24': 'Student Indicator',
        '25': 'Religion',
        '26': "Mother's Maiden Name",
        '27': 'Nationality',
        '28': 'Ethnic Group',
        '29': 'Contact Reason',
        '30': "Contact Person's Name",
        '31': "Contact Person's Telephone Number",
        '32': "Contact Person's Address",
        '33': "Next of Kin/Associated Party's Identifiers",
        '34': 'Job Status',
        '35': 'Race',
        '36': 'Handicap',
        '37': 'Contact Person Social Security Number',
        '38': 'Next of Kin Birth Place',
        '39': 'VIP Indicator',
        '40': 'Next of Kin Telecommunication Information',
        '41': "Contact Person's Telecommunication Information"
    },
    'OBR': {
        '1': 'Set ID - OBR',
        '2': 'Placer Order Number',
        '3': 'Filler Order Number',
        '4': 'Universal Service Identifier',
        '5': 'Priority',
        '6': 'Requested Date/Time',
        '7': 'Observation Date/Time #',
        '8': 'Observation End Date/Time #',
        '9': 'Collection Volume *',
        '10': 'Collector Identifier *',
        '11': 'Specimen Action Code *',
        '12': 'Danger Code',
        '13': 'Relevant Clinical Information',
        '14': 'Specimen Received Date/Time',
        '15': 'Specimen Source',
        '16': 'Ordering Provider',
        '17': 'Order Callback Phone Number',
        '18': 'Placer Field 1',
        '19': 'Placer Field 2',
        '20': 'Filler Field 1 +',
        '21': 'Filler Field 2 +',
        '22': 'Results Rpt/Status Chng - Date/Time +',
        '23': 'Charge to Practice +',
        '24': 'Diagnostic Serv Sect ID',
        '25': 'Result Status +',
        '26': 'Parent Result +',
        '27': 'Quantity/Timing',
        '28': 'Result Copies To',
        '29': 'Parent Results Observation Identifier',
        '30': 'Transportation Mode',
        '31': 'Reason for Study',
        '32': 'Principal Result Interpreter +',
        '33': 'Assistant Result Interpreter +',
        '34': 'Technician +',
        '35': 'Transcriptionist +',
        '36': 'Scheduled Date/Time +',
        '37': 'Number of Sample Containers *',
        '38': 'Transport Logistics of Collected Sample *',
        '39': "Collector's Comment *",
        '40': 'Transport Arrangement Responsibility',
        '41': 'Transport Arranged',
        '42': 'Escort Required',
        '43': 'Planned Patient Transport Comment',
        '44': 'Procedure Code',
        '45': 'Procedure Code Modifier',
        '46': 'Placer Supplemental Service Information',
        '47': 'Filler Supplemental Service Information',
        '48': 'Medically Necessary Duplicate Procedure Reason',
        '49': 'Result Handling',
        '50': 'Parent Universal Service Identifier',
        '51': 'Observation Group ID',
        '52': 'Parent Observation Group ID',
        '53': 'Alternate Placer Order Number',
        '54': 'Parent Order'
    },
    'OBX': {
        '1': 'Set ID - OBX',
        '2': 'Value Type',
        '3': 'Observation Identifier',
        '4': 'Observation Sub-ID',
        '5': 'Observation Value',
        '6': 'Units',
        '7': 'References Range',
        '8': 'Interpretation Codes',
        '9': 'Probability',
        '10': 'Nature of Abnormal Test',
        '11': 'Observation Result Status',
        '12': 'Effective Date of Reference Range',
        '13': 'User Defined Access Checks',
        '14': 'Date/Time of the Observation',
        '15': "Producer's ID",
        '16': 'Responsible Observer',
        '17': 'Observation Method',
        '18': 'Equipment Instance Identifier',
        '19': 'Date/Time of the Analysis',
        '20': 'Observation Site',
        '21': 'Observation Instance Identifier',
        '22': 'Mood Code',
        '23': 'Performing Organization Name',
        '24': 'Performing Organization Address',
        '25': 'Performing Organization Medical Director',
        '26': 'Patient Results Release Category',
        '27': 'Root Cause',
        '28': 'Local Process Control'
    }
}

# ADT Event Codes
ADT_CODES = {
    'A01': 'Admit/visit notification',
    'A02': 'Transfer a patient',
    'A03': 'Discharge/end visit',
    'A04': 'Register a patient',
    'A05': 'Pre-admit a patient',
    'A06': 'Change an outpatient to an inpatient',
    'A07': 'Change an inpatient to an outpatient',
    'A08': 'Update patient information',
    'A09': 'Patient departing - tracking',
    'A10': 'Patient arriving - tracking',
    'A11': 'Cancel admit/visit notification',
    'A12': 'Cancel transfer',
    'A13': 'Cancel discharge/end visit',
    'A14': 'Pending admit',
    'A15': 'Pending transfer',
    'A16': 'Pending discharge',
    'A17': 'Swap patients',
    'A18': 'Merge patient information',
    'A19': 'Patient query',
    'A20': 'Bed status update',
    'A21': 'Patient goes on a leave of absence',
    'A22': 'Patient returns from a leave of absence',
    'A23': 'Delete a patient record',
    'A24': 'Link patient information',
    'A25': 'Cancel pending discharge',
    'A26': 'Cancel pending transfer',
    'A27': 'Cancel pending admit',
    'A28': 'Add person information',
    'A29': 'Delete person information',
    'A30': 'Merge person information',
    'A31': 'Update person information',
    'A32': 'Cancel patient arriving - tracking',
    'A33': 'Cancel patient departing - tracking',
    'A34': 'Merge patient information - patient ID only',
    'A35': 'Merge patient information - account number only',
    'A36': 'Merge patient information - patient ID and account number',
    'A37': 'Unlink patient information',
    'A38': 'Cancel pre-admit',
    'A39': 'Merge person - patient ID',
    'A40': 'Merge patient - patient identifier list',
    'A41': 'Merge account - patient account number',
    'A42': 'Merge visit - visit number',
    'A43': 'Move patient information - patient identifier list',
    'A44': 'Move account information - patient account number',
    'A45': 'Move visit information - visit number',
    'A46': 'Change patient ID',
    'A47': 'Change patient identifier list',
    'A48': 'Change alternate patient ID',
    'A49': 'Change patient account number',
    'A50': 'Change visit number',
    'A51': 'Change alternate visit ID',
    'A52': 'Cancel leave of absence for a patient',
    'A53': 'Cancel patient returns from a leave of absence',
    'A54': 'Change attending doctor',
    'A55': 'Cancel change attending doctor',
    'A60': 'Update allergy information',
    'A61': 'Change consulting doctor',
    'A62': 'Cancel change consulting doctor'
}